services:
  ex_search:
    build: ./
    ports:
      - "8060:8060"
    volumes:
      - ./ex_search:/app/ex_search
      - ./data/db:/app/db
      - ./data/log:/app/log
    depends_on:
      - selenium
  selenium:
    container_name: selenium-chrome
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    shm_size: "2gb"
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
  worker_sofmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker_sofmap
    command: celery -A tasks worker --loglevel=info --concurrency=1 -Q sofmap_work_queue
    volumes:
      - ./ex_search:/app/ex_search
      - ./data/db:/app/db
      - ./data/log:/app/log
    depends_on:
      - redis