services:
  ex_search:
    build: ./
    ports:
      - "8060:8060"
    volumes:
      - ./ex_search:/app/ex_search
      - ./data/db:/app/db
      - ./data/log:/app/log
    depends_on:
      - selenium
  selenium:
    container_name: selenium-chrome
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    shm_size: "2gb"
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
